export const BUTTON_NEXT = 'Next'
export const BUTTON_PREV = 'Prev'
export const BUTTON_SEE_MORE = 'See more'
export const TABLE_POKEMON_NAME = 'Pokemon name'
export const TABLE_ACTIONS = 'Actions'
export const ALT_POKEBALL_SPINNER = 'Pokeball spinner'
export const ALT_POKEMON_LOGO = 'Pokemon logo'
